mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('posts/', include('posts.urls')),
    path('profiles/', include('users.urls')),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    path('register/',user_views.register, name = 'register'),
    
]

posts/urls.py
from django.urls import path
from . import views
from posts.views import(
    postSentListView,
    postReceivedListView,
    postDetailView,
    postCreateCover
)
import posts.views as post_views

urlpatterns = [
path('sent/', postSentListView.as_view(), name = 'post-sent'),
path('received/', postReceivedListView.as_view(), name = 'post-received'),
#path('new/', postCreateView.as_view(), name = 'post-create'),
path('<int:pk>/', postDetailView.as_view(), name = 'post-detail'),
path('schedule/<int:pk>/shift/<int:alt_pk>/new_cover', post_views.postCreateCover, name = 'post-create')
]

website/urls.py
from django.urls import path
from . import views
from website.views import (
    scheduleListView,
    scheduleDetailView,
    shiftDetailView
)



urlpatterns = [
    path('', scheduleListView.as_view(), name = 'website-home'),
    path('schedule/<int:pk>/', scheduleDetailView.as_view(), name = 'schedule-detail'),
    path('about/', views.about, name='website-about'),
    #path('search/', searchShiftListView.as_view(), name = 'shift-search'),
    path('schedule/<int:pk>/shift/<int:alt_pk>/',shiftDetailView.as_view(), name = 'shift-detail')

    

 
]

website/models.py
from __future__ import unicode_literals
from django.db import models
#from django.contrib.auth.models import User
import datetime 
from django.urls import reverse
from django.db.models import Q
from django.core.exceptions import ValidationError
from users.models import User
#from users.models import Roles
class mainSchedule(models.Model):
    date_started = models.DateField()
    date_end = models.DateField() 
    def __str__(self):
        a = self.date_started.strftime("%m/%d/%Y")
        b = self.date_end.strftime("%m/%d/%Y")
        return a + '-' + b
class schedule(models.Model):
    user = models.ForeignKey(User ,on_delete = models.CASCADE)
    hours = models.PositiveIntegerField(default = 0)
    main_sched = models.ForeignKey(mainSchedule , on_delete = models.CASCADE)


    def __str__(self):
        a = self.main_sched.date_started.strftime("%m/%d/%Y")
        b = self.main_sched.date_end.strftime("%m/%d/%Y")
        return a + ' - '+ b + '-' + str(self.user.profile.name)

    def get_absolute_url(self):
        return reverse('schedule-detail', kwargs={'pk': self.pk})






class shift(models.Model):
    
    #shiftID = models.AutoField(primary_key = True)
    #person = models.ForeignKey(User, on_delete = models.CASCADE)
    day = models.DateField(u'Day of the event', help_text=u'Day of the event')
    start_time = models.TimeField(u'Starting time', help_text=u'Starting time')
    end_time = models.TimeField(u'Final time', help_text=u'Final time')
    role = models.ForeignKey('users.Roles', on_delete = models.CASCADE)
    schedule = models.ForeignKey(schedule, on_delete = models.CASCADE)
    #def check_role(self , position , ):
    #    wrong_role = False
     #   if position not in person.Roles:
      #      wrong_role = True
        # return wrong_role
    def __str__(self):
        a = self.day.strftime("%m/%d/%Y")
        b = self.start_time.strftime('%I:%M %p')
        c = self.end_time.strftime('%I:%M %p')
        d = self.role
        return a + ' : ' + b + ' - ' + c +  ' : ' + str( d)
    
    def check_cover(self):
        options = schedule.objects.filter(Q(main_sched =  self.schedule.main_sched) & Q(hours__lt = 40))
        options.filter(Q(user__profile__roles__name__icontains = self.role) & ~Q(shift__day = self.day))
        result = User.objects.filter(schedule__in = options)
        return result

    def check_swap(self):
        options = User.objects.filter(Q(user__profile__roles__name__icontains = self.role) & ~Q(shift__day = self.day)) 
        return options

    '''    
    def check_overlap(self,start_time, end_time, fixed_start, fixed_end):
        overlap = False
        if(start_time == fixed_start or end_time == fixed_end):
            overlap = True
        elif(start_time >= fixed_start and end_time <= fixed_end) or (end_time >= fixed_start and end_time <= fixed_end):
            overlap = True
        elif (start_time <= fixed_start and end_time >= fixed_end):
            overlap = True
        return overlap
    
    def check_init(self):
        if self.end_time > self.start_time:
            raise ValidationError("End time must be after start time.")
        events = shift.objects.filter(day=self.day)
        if events.exists():
            for event in events:
                if self.check_overlap(event.start_time, event.end_time, self.start_time, self.end_time):
                    raise ValidationError(
                        'There is an overlap with another event: ' + str(event.day) + ', ' + str(
                            event.start_time) + '-' + str(event.end_time))


    #shifts = models.ForeignKey(shift, on_delete = models.SET_NULL, null = True)
'''

website/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView
)
from django.db.models import Q
from .models import schedule ,shift
from users.views import Profile
from datetime import datetime
class scheduleListView(LoginRequiredMixin,ListView):
    model = schedule
    template_name = 'website/home.html'
    context_object_name = 'schedules'

    def get_queryset(self):
        user = self.request.user
        schedule_list = schedule.objects.filter(user = user)
        #sched = schedule_list.order_by('-date_started')
        return schedule_list

class scheduleDetailView(DetailView):
    model = schedule

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(scheduleDetailView, self).get_context_data(**kwargs)
        context['shifts'] = shift.objects.filter(schedule__user = user, schedule = self.kwargs.get('pk')).order_by('-day')
        return context

class shiftDetailView(DetailView):
    model = shift      
    template_name = 'website/shift_detail.html'
    context_object_name = 'shift'

def home(request):
    return render(request, 'website/home.html')

def about(request):
    return render(request, 'website/about.html', {'title': 'About'})

website/templates/website/about.html
{% extends "website/base.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

website/templates/website/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        
        <link rel="stylesheet" type="text/css" href="{% static 'website/main.css' %}">
    

        {% if title %} 
            <title>Cover - {{ title }}</title> <!-- If {within brackets its a variable} -->
        {% else %}
            <title>Cover</title>
        {% endif %}



        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <!-- Brand/logo -->
            <a class="navbar-brand" href="#">Logo</a>
    
    <!-- Links -->
            
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'website-home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'website-about' %}">About</a>
                </li>
            </ul>
            <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#"><span class="fas fa-sign-in-alt"></span> New Post </a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'profile' user.profile.pk %}"><span class="fas fa-sign-in-alt"></span> Profile </a>
                        </li>
                    
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}"><span class="fas fa-sign-in-alt"></span> Logout </a>
                        </li>
                    {% endif %}

            </ul>
        </nav>
        <div class="jumbotron">
            <h1>Cover</h1>
                <p>Scheduler for the workplace</p>
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>   
    <body>
        {% block content %} {% endblock content %}
    </body>
</html>

website/templates/website/home.html
{% extends "website/base.html" %}
{% block content %}
{% for schedule in schedules %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <h2> <a class = "mr-2" href="{% url 'schedule-detail' pk=schedule.pk %}" > {{schedule}}</a></h2>
            </div>
        </div>
    </article>
{% endfor %}

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light"><a href="{% url 'post-sent' %}">Posts Sent</a></li>
                <li class="list-group-item list-group-item-light"><a href="{% url 'post-received' %}">Inbox</a></li>
                <li class="list-group-item list-group-item-light"><a href="{% url 'profile-search' %}">Profiles</a></li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>
{% endblock content %}

website/templates/website/schedule_detail.html
{% extends "website/base.html" %}
{% block content %}
<a class = "mr-2" href="#" > {{object}} </a>
{% for shift in shifts %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <h2> <a class = "mr-2" href="{% url 'shift-detail' schedule.pk shift.pk %}" > {{shift}}</a></h2>
            </div>
        </div>
    </article>
{% endfor %}
{% endblock content %}

website/templates/website/search_shift.html
{% extends "website/base.html" %}
{% block content %}
<h1>Search Results</h1>

<ul>
  {% for profile in shift_list %}
    <li>
      {{ profile }}
    </li>
  {% endfor %}
</ul>
{% endblock %}

website/templates/website/shift_detail.html
{% extends "website/base.html" %}
{% block content %}
    <p>
    <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        {{shift}}
    </a>
    </p>
    <div class="collapse" id="collapseExample">
        <div class="card card-body">
            <button type="button" class="btn btn-primary btn-sm btn-block"> Find Coverage </button>
            <button type="button" class="btn btn-secondary btn-sm btn-block">Swap Shifts </button>
        </div>
    </div>

{% endblock content %}

website/templates/website/user_home.html
{% extends "website/base.html" %}
{% block content %}
{% for schedule in schedules %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <h2> <a class = "mr-2" href="{% url 'schedule-detail' pk=schedule.pk %}" > {{schedule}}</a></h2>
            </div>
        </div>
    </article>
{% endfor %}
{% endblock content %}